### ISSUE TITLE
Trying to fetch the private_ip_address that is dynamically created to use it in a vnet dns configuration update

### ISSUE THREAD

**Issue by rs-joz** [haflidif/terraform-azurerm-dns-private-resolver#19]
Hi,
I must say this module is super nice, I create a DNS Private resolver easily. (see output)

  ```
# module.dns_private_resolver["test-dns-resolver"].azurerm_private_dns_resolver.private_dns_resolver will be created
  + resource "azurerm_private_dns_resolver" "private_dns_resolver" {
      + id                  = (known after apply)
      + location            = "eastus"
      + name                = "test-dns-resolver"
      + resource_group_name = "test-rg"
      + tags                = {
          + "Configuration" = "Terraform"
          + "Environment"   = "Development"
        }
      + virtual_network_id  = (known after apply)
    }

  # module.dns_private_resolver["test-dns-resolver"].azurerm_private_dns_resolver_inbound_endpoint.private_dns_resolver_inbound_endpoint["test-dns-resolver-inbound-private-endpoint"] will be created
  + resource "azurerm_private_dns_resolver_inbound_endpoint" "private_dns_resolver_inbound_endpoint" {
      + id                      = (known after apply)
      + location                = "eastus"
      + name                    = "test-dns-resolver-inbound-private-endpoint"
      + private_dns_resolver_id = (known after apply)
      + tags                    = {
          + "Configuration" = "Terraform"
          + "Environment"   = "Development"
        }

      + ip_configurations {
          + private_ip_address           = (known after apply)
          + private_ip_allocation_method = "Dynamic"
          + subnet_id                    = (known after apply)
        }
    }
```

How can I use the "private_ip_address" value further down my code?

I've been following this: https://developer.hashicorp.com/terraform/language/expressions/references
Which states:
module.<MODULE NAME> is an value representing the results of [a module block](https://developer.hashicorp.com/terraform/language/modules/syntax).

If the corresponding module block does not have either count nor for_each set then the value will be an object with one attribute for each output value defined in the child module. To access one of the module's [output values](https://developer.hashicorp.com/terraform/language/values/outputs), use module.<MODULE NAME>.<OUTPUT NAME>.

If the corresponding module uses for_each then the value will be a map of objects whose keys correspond with the keys in the for_each expression, and whose values are each objects with one attribute for each output value defined in the child module, each representing one module instance.

If the corresponding module uses count then the result is similar to for for_each except that the value is a list with the requested number of elements, each one representing one module instance.

Now, I'm not sure, but can't get into any output (tried to wrap it in a for loop on the output side, still, doesn't work)

Any idea?

Seems like
` module.dns_private_resolver is object with no attributes`

While trying to figure-out the structure, I've built a simple output:
```
output "dns_private_resolver" {
  value = {
    "dns_private_resolver_id"                    = module.dns_private_resolver["test-dns-resolver"].dns_resolver["dns_resolver_id"]
    "dns_private_resolver_inbound_endpoint_id"   = module.dns_private_resolver["test-dns-resolver"].dns_resolver["dns_inbound_endpoints"].test-dns-resolver-inbound-private-endpoint["inbound_endpoint_id"]
    "dns_private_resolver_inbound_endpoint_name" = module.dns_private_resolver["test-dns-resolver"].dns_resolver["dns_inbound_endpoints"].test-dns-resolver-inbound-private-endpoint["inbound_endpoint_name"]
  }
}
```
There's no way to query into the IP address, well... at least I don't see a way. Which is an issue, because, one might want to take this IP address and set it on a VNET dns configuration.

**Comment by haflidif** [comment]
Hey @rs-joz 

Thank you very much for your kind words about the module and your support, hope it's serving you well.

I've fixed the issue you've posted, updated the documentation, and given an example [here](https://github.com/haflidif/terraform-azurerm-dns-private-resolver#example-3) on how to get the output for the Private IP Address to use further within your Virtual Network Custom DNS Servers.

The newest version with the fix is now the latest version or [1.0.12](https://github.com/haflidif/terraform-azurerm-dns-private-resolver/releases/tag/1.0.12)

feel free to post any other issues if they occur and I will try to fix them as soon as possible.
